### ISSUE TITLE
HybridMC

### ISSUE THREAD

**Issue by WinixMC** [radmanplays/radmanplays.github.io#10]
### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

Welcome to.... HYBRID MC!

Here we have an eaglercraft server that has the following:

-Factions!
-Kit PVP!
-Bedwars!
-And MORE!

Here are the important figures:

Founders: Deluxe and Bestplayer

Owner: Erdii

Developers:
winixmc

Click the link below to join!

https://discord.gg/CmvcBmWXGD

**Comment by radmanplays** [comment]
> ### replit server or 24/7 eaglercraft server?
> * [x]  the server is made in replit
> * [ ]  the server is made in an paid,24/7 host
> 
> ### about server
> Welcome to.... HYBRID MC!
> 
> Here we have an eaglercraft server that has the following:
> 
> -Factions! -Kit PVP! -Bedwars! -And MORE!
> 
> Here are the important figures:
> 
> Founders: Deluxe and Bestplayer
> 
> Owner: Erdii
> 
> Developers: winixmc
> 
> Click the link below to join!
> 
> https://discord.gg/CmvcBmWXGD

server ip?

**Comment by WinixMC** [comment]
Replit: wss://play.hybridmc.repl.co/
Java: saturn.cxmpute.com:10000

**Comment by radmanplays** [comment]
> Replit: wss://play.hybridmc.repl.co/ Java: saturn.cxmpute.com:10000

your server has been added!
