### ISSUE TITLE
DragonXv3 not working

### ISSUE THREAD

**Issue by jawndough96** [radmanplays/radmanplays.github.io#110]
### text

when i try to open dragonXv3 via radmanplays.github.io-main.zip/radmanplays.github.io-main/hacked/dragonxv3-1.8.8/index.html,  it shows me an error "HTTP please, do not open this file locally, run a local HTTP server and load it via HTTP" this is downlaoded as an html, but I figured it would work.

**Comment by radmanplays** [comment]
just download it from here : https://radmanplays.github.io/downloads/
