### ISSUE TITLE
you know this is ilegal right?

### ISSUE THREAD

**Issue by bloohacked** [radmanplays/radmanplays.github.io#113]
you should take this down asap

**Comment by BasToTheMax** [comment]
Why is this illegal?

**Comment by bloohacked** [comment]
piracy

**Comment by radmanplays** [comment]
tlauncher  pirates minecraft too but mojang dosnt take it down so this repo is fine

**Comment by bloohacked** [comment]
they do care about eaglercraft though

**Comment by daniel-here** [comment]
not taken down yet, so i'll keep playing.

**Comment by bloohacked** [comment]
ok, I was just putting this up as a heads up
