### ISSUE TITLE
How do you make a website to put a server on?

### ISSUE THREAD

**Issue by TheCodingMasterPiece** [radmanplays/radmanplays.github.io#2]
I cant figure out how to make a server and its driving me crazy. Im trying to make an smp for my school before i get back so if you know please tell me. Also could you paste the embed code of your website on here so i can put it on my site?

**Comment by radmanplays** [comment]
do you want the server to be 1.8 or 1.5.2? if you want a 1.5.2 server you need to make a lan world in your school. also whats your site link? and also please dont bookmark my site in your school because it will be easier for teachers to find it and block it in your school.

**Comment by GsDeluxe** [comment]
you can do 2 things:

1) make a python localhost server using flask 

or

2) make a free netlify site and host it on there

hope this helps :)

**Comment by papi25** [comment]
https://www.youtube.com/watch?v=T1wLqlcDUAg&t=306s
