### ISSUE TITLE
Heroku Deployment Broken

### ISSUE THREAD

**Issue by carricktoupe** [radmanplays/radmanplays.github.io#204]
States that static buildpack is broken, needs to be updated to NGINX. if someone could point me in the right direction to update it, i'd be happy to work on it. 

-> Building on the Heroku-22 stack
-----> Using buildpack: https://github.com/heroku/heroku-buildpack-static
-----> Static HTML app detected
       ## WARNING: `heroku-buildpack-static` is deprecated
       This buildpack is deprecated and is no longer being maintained.
       If you are using this project, you can transition over to NGINX via an NGINX buildpack.
       Use your project's existing configuration.
       To find the NGINX configuration generated by the heroku-buildpack-static you can run:
       ```
       $ heroku run bash
       ~ $ bin/config/make-config
       ~ $ cat config/nginx.conf
       ```
       These commands will output your current NGINX config generated from your `static.json` contents.
       - Write these contents to your local repo at `config/nginx.conf.erb`, commit them to git.
       - Replace path logic that previously used `mruby` with static logic.
       - Configure your app to use the NGINX buildpack via `heroku buildpacks:add heroku-community/nginx`.
       - Remove this buildpack via `heroku buildpacks:remove heroku-community/static` (or `heroku buildpacks:remove https://github.com/heroku/heroku-buildpack-static`).
Stack heroku-22 is not supported!
 !     Push rejected, failed to compile Static HTML app.
 !     Push failed

**Comment by radmanplays** [comment]
fixed i think
