### ISSUE TITLE
Asspixel (BedWar)

### ISSUE THREAD

**Issue by ComputerCode1** [radmanplays/radmanplays.github.io#226]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

The servers are not working the Bedwars servers lobby it is not working

### Screenshots

![Screenshot 2023-12-16 143351](https://github.com/radmanplays/radmanplays.github.io/assets/143649278/489ad533-6b1d-4383-8437-884fa136c786)

### Discord/revolt server

https://discord.gg/N7pTw2Dk4p

### server's website

Eagerlercraft

### server ip

wss://web.asspixel.net/CAPixel/

**Comment by radmanplays** [comment]
already added

**Comment by ComputerCode1** [comment]
Thank you for your response

**Comment by ComputerCode1** [comment]
I Have been Ip Ban from the server My user is Hack_21 Can you some how fix
it?

**Comment by radmanplays** [comment]
im not the owner of the server

**Comment by ComputerCode1** [comment]
Oh okay.
