### ISSUE TITLE
Lifesteal SMP

### ISSUE THREAD

**Issue by firstlynx-sys** [radmanplays/radmanplays.github.io#230]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

Lifesteal SMP is the best Eaglercraft Lifesteal server, with great economy, nice admins, anticheat, and other features that keep you coming back! We are resetting on 12/25/23 so joining will keep you on the same loot pool as other players.

### Discord/revolt server

https://discord.gg/VPeDPKu3dc

### server's website

https://eaglercraftlifesteal.tebex.io/

### server ip

wss://lifesteal.matthewkrupenya.repl.co/server

**Comment by Himalayanllama** [comment]
What plugins your server have

**Comment by firstlynx-sys** [comment]
> What plugins your server have

do i list them out or name the features?

features:
- economy
- shop
- homes
- tpa
- jobs
- trading
- quests
- GOOD anticheat
- backpacks
- lifesteal
- cheep and good ranks
- chat games
- warps
- clans
- kits
- many players
- nice staff
- frequent updates

**Comment by firstlynx-sys** [comment]
also i got a nice deal on the Replit deal a long time ago so yeah its replit but it has 8gb ram

**Comment by firstlynx-sys** [comment]
added
