### ISSUE TITLE
samMFM

### ISSUE THREAD

**Issue by luffy23a** [radmanplays/radmanplays.github.io#235]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [X] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

a normal eagle craftserver with an multiplayer gamemode and no texture packs,i create to make you have fun with your friends,nothing more

### server ip

wss://1234

**Comment by firstlynx-sys** [comment]
ip doesnt work

**Comment by luffy23a** [comment]
I now I'm having some problems

Il giorno sab 30 dic 2023 alle ore 03:16 FirstLynx ***@***.***>
ha scritto:
