### ISSUE TITLE
SpiderSMP

### ISSUE THREAD

**Issue by Herobrine12343** [radmanplays/radmanplays.github.io#254]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [X] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

I went to do my own public server that callad **Spider Smp**.It will have pvp, crystel, survival, creative and etc.

### Screenshots

![download](https://github.com/radmanplays/radmanplays.github.io/assets/119780248/ac674e85-2a6d-4709-81b0-a357ca450319)
![download](https://github.com/radmanplays/radmanplays.github.io/assets/119780248/4d2c3b7e-845c-4e5a-bbf1-9e922e7be898)

### Discord/revolt server

https://discord.com/channels/1189110266244366427/1189110266244366429

### server ip

wss://SpiderSmp.mc

**Comment by Herobrine12343** [comment]
Can you make this Server for me?

**Comment by radmanplays** [comment]
this serverlist is for existing servers only
