### ISSUE TITLE
kitpvp server

### ISSUE THREAD

**Issue by IsThisAlongNameYesItIsMaybe** [radmanplays/radmanplays.github.io#28]
### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

This server is just simple KitPVP, It doesn't have an official name. It has good online time because it has 2 bots to keep it online. It is hosted on Aternos but uses replit to be able to be joined on eagler.

the server ip is not a mistake

### server ip

wss://play--longnames1.repl.co/

**Comment by radmanplays** [comment]
> wss://play--longnames1.repl.co/

added
