### ISSUE TITLE
Vibe Network

### ISSUE THREAD

**Issue by JaegerBomBYT** [radmanplays/radmanplays.github.io#29]
### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

🔥 **VIBE NETWORK** 🔥   [1.8-1.20.1] 
THE BEST 1.20.1 EAGLER SERVER (NO REPLIT)

Java & Bedrock IP: **vibemc.xyz** [Default Port]
Eagler IP: **wss://vibemc.xyz**

- Custom survival with Jobs, Custom enchants, economy and factions. :diamond_pickaxe:
- Practice PVP with EVENTS, FFA, RANKED PVP and LEADERBOARDS TO GRIND :diamond_sword:
- Bedwars / Skywars / The Pit coming soon!!!
- Discord: https://discord.gg/vX9sSnJHSd

### server ip

wss://vibemc.xyz

**Comment by radmanplays** [comment]
added
