### ISSUE TITLE
Flame Network

### ISSUE THREAD

**Issue by Matthewizlitz** [radmanplays/radmanplays.github.io#34]
### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

We are a network like hypixel like a eagler hypixel 👍 it is a 24/7 host with paid with no replit needed. we are starting with game mode survival

### server ip

flame.minecraft.pe:25009

**Comment by radmanplays** [comment]
> ### replit server or 24/7 eaglercraft server?
> * [ ]  the server is made in replit
> * [x]  the server is made in an paid,24/7 host
> 
> ### about server
> We are a network like hypixel like a eagler hypixel 👍 it is a 24/7 host with paid with no replit needed. we are starting with game mode survival
> 
> ### server ip
> flame.minecraft.pe:25009

sorry but this is server list is for eaglercraft servers or servers that support eaglercraft.
if you don't have any other questions tell me to close this issue

**Comment by Matthewizlitz** [comment]
this supports eaglercraft :)

**Comment by radmanplays** [comment]
> this supports eaglercraft :)

whats the eaglercraft ip?

**Comment by radmanplays** [comment]
> this supports eaglercraft :)

please respond or ill close this issue

**Comment by Matthewizlitz** [comment]
wss://flamemc.repl.co

**Comment by Matthewizlitz** [comment]
what do you mean wss://flamemc.repl.co.

Domain is getting worked on soon

Server was down today tommrow it will up

**Comment by Matthewizlitz** [comment]
alr tuesday is when ip is released I will let you know <3

**Comment by radmanplays** [comment]
> alr tuesday is when ip is released I will let you know <3

k
