### ISSUE TITLE
Venstone

### ISSUE THREAD

**Issue by Limeen** [radmanplays/radmanplays.github.io#35]
### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

Venstone is a French **Minecraft survival server** open to everyone, for all platforms.
Our server offers a gaming experience close to vanilla, with the addition of useful commands such as homes, tpa, etc..

The server is compatible on Java & Bedrock as well,
The language spoken is **French**, but go for a walk if you are curious!

Official website: https://venstone.ddns.net/

## Screenshot ##
![mc3](https://github.com/radmanplays/radmanplays.github.io/assets/56938765/36e919ae-4831-49d7-9b80-16f165fd960d)
![2023-06-26-19 57 28](https://github.com/radmanplays/radmanplays.github.io/assets/56938765/73e6d99d-6e85-4916-b3a8-39f24b595935)
![image](https://github.com/radmanplays/radmanplays.github.io/assets/56938765/faed8242-fd30-4c7c-b22d-ce6dcb111488)

### server ip

wss://venstone.ddns.net:8082

**Comment by Matthewizlitz** [comment]
doesnt work

**Comment by radmanplays** [comment]
> ### replit server or 24/7 eaglercraft server?
> * [ ]  the server is made in replit
> * [x]  the server is made in an paid,24/7 host
> 
> ### about server
> Venstone is a French **Minecraft survival server** open to everyone, for all platforms. Our server offers a gaming experience close to vanilla, with the addition of useful commands such as homes, tpa, etc..
> 
> The server is compatible on Java & Bedrock as well, The language spoken is **French**, but go for a walk if you are curious!
> 
> Official website: https://venstone.ddns.net/
> 
> ## Screenshot
> ![mc3](https://user-images.githubusercontent.com/56938765/261562862-36e919ae-4831-49d7-9b80-16f165fd960d.png) ![2023-06-26-19 57 28](https://user-images.githubusercontent.com/56938765/261563018-73e6d99d-6e85-4916-b3a8-39f24b595935.png) ![image](https://user-images.githubusercontent.com/56938765/261563270-faed8242-fd30-4c7c-b22d-ce6dcb111488.png)
> 
> ### server ip
> wss://venstone.ddns.net:8082

im currently working on a "more info" button in the serverlist. ill add your server when the button is done

**Comment by Limeen** [comment]
Okay!

**Comment by radmanplays** [comment]
your server has been added!
https://radmanplays.github.io/serverlist/
https://radmanplays.github.io/serverlist/info/venstone/
