### ISSUE TITLE
server name

### ISSUE THREAD

**Issue by Felixkaug162** [radmanplays/radmanplays.github.io#36]
### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

nothing

### server ip

glitchy.mc-server.eu

**Comment by radmanplays** [comment]
> ### replit server or 24/7 eaglercraft server?
> * [ ]  the server is made in replit
> * [x]  the server is made in an paid,24/7 host
> 
> ### about server
> nothing
> 
> ### server ip
> glitchy.mc-server.eu

sorry but this serverlist is for eaglercraft server only!
