### ISSUE TITLE
Client Removal - EaglerReborn

### ISSUE THREAD

**Issue by Cerealistic** [radmanplays/radmanplays.github.io#45]
### text

I represent the EaglerReborn team by asking you to remove this client, before Mojang gets to it.

**Comment by PilotNord** [comment]
Uh oh.

**Comment by Cerealistic** [comment]
Yes, this requires drastic measures. If it is not removed I will have to file a DMCA takedown request as per my client.

**Comment by radmanplays** [comment]
> ### text
> 
> I represent the EaglerReborn team by asking you to remove this client, before Mojang gets to it.

oh sorry I forgot to remove it. I'll remove it now

**Comment by Cerealistic** [comment]
> > ### text
> > I represent the EaglerReborn team by asking you to remove this client, before Mojang gets to it.
> 
> oh sorry I forgot to remove it. I'll remove it now. I was too busy I forgot to remove it

Thank you for the quick reply, and I wish you the best in future endeavors.
