### ISSUE TITLE
Olivcraft

### ISSUE THREAD

**Issue by Olive4u** [radmanplays/radmanplays.github.io#48]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

A parkour wip smp

### server ip

wss://olivcraft.repl.co

**Comment by radmanplays** [comment]
your server will be added in the next website update
