### ISSUE TITLE
CerealNetwork

### ISSUE THREAD

**Issue by Cerealistic** [radmanplays/radmanplays.github.io#49]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

1.17.1 Factions server featuring netherite, ranks, webstore, and more. Can only be accessed by CerealClient.

### Discord/revolt server

dsc.gg/cerealnet

### server's website

cerealnet.work

### server ip

wss://cerealnet.work

**Comment by Cerealistic** [comment]
if you didn't already know, the server's release is on September 29th.

**Comment by radmanplays** [comment]
> ### by making a request to add your server you must check these boxes
> * [x]  I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
> * [x]  I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
> * [x]  I know that by making a request to add my server to the serverlist anyone can join my server
> * [x]  I know that by making a request you dont make me a server and add it to the serverlist
> * [ ]  I just checked all of these boxes without reading the labels
> 
> ### replit server or 24/7 eaglercraft server?
> * [ ]  the server is made in replit
> * [x]  the server is made in an paid,24/7 host
> 
> ### about server
> 1.17.1 Factions server featuring netherite, ranks, webstore, and more. Can only be accessed by CerealClient.
> 
> ### Screenshots
> _No response_
> 
> ### Discord/revolt server
> dsc.gg/cerealnet
> 
> ### server's website
> cerealnet.work
> 
> ### server ip
> wss://cerealnet.work

your server will be added in the next update website

**Comment by Cerealistic** [comment]
@radmanplays Once CerealClient is completed I will give you an offline download, CerealNetwork has a protocol that only verified client users can join (CerealClient, Lunar, Badlion)

**Comment by radmanplays** [comment]
> @radmanplays Once CerealClient is completed I will give you an offline download, CerealNetwork has a protocol that only verified client users can join (CerealClient, Lunar, Badlion)

k but can you give me the web folder too?

**Comment by Cerealistic** [comment]
@radmanplays that would leak client branding.

**Comment by radmanplays** [comment]
> @radmanplays that would leak client branding.

ok
