### ISSUE TITLE
School SMP 

### ISSUE THREAD

**Issue by papi25** [radmanplays/radmanplays.github.io#5]
### replit server or 24/7 eaglercraft server?

- [x] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

an smp for content creators and normal players alike. join the smp today and have some fun!
wss://schoolsmp-1--pigsalotcoder.repl.co/

**Comment by radmanplays** [comment]
> ### replit server or 24/7 eaglercraft server?
> * [x]  the server is made in replit
> * [ ]  the server is made in an paid,24/7 host
> 
> ### about server
> an smp for content creators and normal players alike. join the smp today and have some fun! wss://schoolsmp-1--pigsalotcoder.repl.co/

ill add it to the serverlist
