### ISSUE TITLE
Anime craft

### ISSUE THREAD

**Issue by XSeries5530** [radmanplays/radmanplays.github.io#56]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [X] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] #59
- [ ] the server is made in an paid,24/7 host

### about server

This is a server about anime

### server's website

https://ec-x-188.luciuscuevas.repl.co/

### server ip

wss://ec-x-188.luciuscuevas.repl.co/

**Comment by XSeries5530** [comment]
Bruh I did

**Comment by XSeries5530** [comment]
I'll give you this
![ca8d5dee5e7f539baa502bccf4e889f9](https://github.com/radmanplays/radmanplays.github.io/assets/120821571/3f0edf63-e401-4c41-a1a1-63dff43e0a24)

**Comment by radmanplays** [comment]
your server has been added

**Comment by XSeries5530** [comment]
Smp is not working so can you remove it please and ig add my new smp
