### ISSUE TITLE
CraftClue

### ISSUE THREAD

**Issue by literally1984** [radmanplays/radmanplays.github.io#58]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

CraftClue is the oldest and best anarchy server in Eaglercraft. It is complete vanilla survival with no rules. It has been running for more than a year, the world size is 30+ GB, and more than 50000 players have registered an account. 

### Screenshots

![CraftClue Icon](https://github.com/radmanplays/radmanplays.github.io/assets/85363779/809e47cf-1894-4035-9f9f-2ef4747b9682)
![CraftClue Spawn](https://github.com/radmanplays/radmanplays.github.io/assets/85363779/938a32fa-ed38-460c-9147-77a769271c86)

### Discord/revolt server

https://discord.com/invite/V54E8rVHg2

### server's website

https://www.craftclue.rocks

### server ip

wss://play.craftclue.rocks

**Comment by radmanplays** [comment]
your server has been added!

**Comment by literally1984** [comment]
Hello, thank you for adding CraftClue to the list. However, I would like to add that CraftClue's IP works with both 1.8.8 and 1.5.2, and it has another IP for 1.5.2, which is wss://legacy.craftclue.rocks

**Comment by radmanplays** [comment]
> wss://play.craftclue.rocks

ok i added the 1.5.2 ip too
