### ISSUE TITLE
Myth's EagMP

### ISSUE THREAD

**Issue by MythicalTrashcan** [radmanplays/radmanplays.github.io#61]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

A 1.5.2 Eaglercraft Server with an SMP currently. The server does support 1.8.8 and can be joined from either 1.5.2 or 1.8.8. 
(1.5 Recommended)

Server will be up for about 23 hours straight. (1 hour downtime for maintenance)

(The server is hosted on my PC and not a paid host (i like money))

### Discord/revolt server

http://rvlt.gg/YPnCttyS/

### server's website

http://www.theludos.com/projects/ (Includes the client for both 1.8 and 1.5 latest with both being modified to have my server in the list.

### server ip

wss://mc.theludos.com (yes, I added wss to a server hosted on my pc through cloudflare)

**Comment by grandpa1946** [comment]
use ngrok instead
btw hosting on pc is not smart
use dedicated system

**Comment by MythicalTrashcan** [comment]
> use ngrok instead btw hosting on pc is not smart use dedicated system

I refuse to pay for a good host or accept a horrible one for free. PC works best for me.

**Comment by grandpa1946** [comment]
allright!

**Comment by radmanplays** [comment]
your server has been added! (sorry it took so long. i was kinda busy)
