### ISSUE TITLE
24/7 server name

### ISSUE THREAD

**Issue by nepaliboy80** [radmanplays/radmanplays.github.io#67]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [X] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

THE_LAST_HOPE1.aternos.me:27718

### Screenshots

THE_LAST_HOPE1.aternos.me:27718

### Discord/revolt server

THE_BLOCK

### server's website

https://aternos.org/server/

### server ip

THE_LAST_HOPE1.aternos.me:27718

**Comment by Edward-ba** [comment]
bro literally checked every single box

**Comment by radmanplays** [comment]
not eagler server
