### ISSUE TITLE
Laid Back Gaming Minecraft ( Java/ Bedrock / Eaglercraft / Cracked )

### ISSUE THREAD

**Issue by Synkstar** [radmanplays/radmanplays.github.io#7]
### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [x] the server is made in an paid,24/7 host

### about server

Bedrock/Java: mc.lbgaming.co
Eaglercraft(1.8): wss://eagler.lbgaming.co
Forums: lbgaming.co
Server info site: https://lbgmc.net
Discord: https://discord.gg/zHNd7TkHMs
Server is hosted on a high end Chicago dedicated server. We currently have an SMP, creative server and skyblock. KitPVP and other game modes are in the works.

I hope that you enjoy your stay on our server and make new friends.

**Comment by radmanplays** [comment]
your server has been added!
