### ISSUE TITLE
Aeon

### ISSUE THREAD

**Issue by HelpMeKill** [radmanplays/radmanplays.github.io#74]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [X] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

fight club,pitfall and survival

### server ip

wss://aeon-network.net/1.8

**Comment by radmanplays** [comment]
about server is to short

**Comment by Edward-ba** [comment]
There is also skyblock but that's in alpha. Survival is based in 1.12.2 with protocol support so players can have things like elytras and shulker boxes in 1.8.8. Pitfall is a hypixel pit knockoff with fishing, stabbing, and permanent upgrades like armor and soup and temp upgrades like cobwebs and obsidian. Fight Club has many different game modes like MLG rush, no debuff, boxing, etc. There is also no limit to the number of bot fights per player.

**Comment by Edward-ba** [comment]
server website: aeon-network.tebex.io

**Comment by Edward-ba** [comment]
its actually a good server add it to the list, it gets like 70-80 players at any given time

**Comment by radmanplays** [comment]
ok i added this server
