### ISSUE TITLE
just to have fun and be friends

### ISSUE THREAD

**Issue by griffinlitteral** [radmanplays/radmanplays.github.io#76]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [X] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [X] the server is made in replit
- [ ] the server is made in an paid,24/7 host

### about server

I will be a server where people can join and have a fun time with no hate or toxicity.

### Screenshots

So far no one has played on the sever

### server ip

relay.shhnowisnottheti.me/

**Comment by griffinlitteral** [comment]
SO for version 1.5.2 me and my friends were playing and we wanted to play together so i made a LAN world and when my friends tried to join it said sever not connected does it have to be a sever for use to play together. Thank you hope you can respond

**Comment by radmanplays** [comment]
> SO for version 1.5.2 me and my friends were playing and we wanted to play together so i made a LAN world and when my friends tried to join it said sever not connected does it have to be a sever for use to play together. Thank you hope you can respond

yeah it has to be a server not a LAN world
