### ISSUE TITLE
Clever-Teaching

### ISSUE THREAD

**Issue by AllforHim0064** [radmanplays/radmanplays.github.io#85]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

Has semi-anarchy survival, Bedwars, Skywars, Spleef, Build Battle, and creative.

### Screenshots

![image](https://github.com/radmanplays/radmanplays.github.io/assets/76498719/bdfe53b1-6c8d-4384-8e2e-f276d8452d6e)
![image](https://github.com/radmanplays/radmanplays.github.io/assets/76498719/9809d0a8-75bb-46b8-b8fd-e9e4a8b7c593)
![image](https://github.com/radmanplays/radmanplays.github.io/assets/76498719/7e21e5ce-8257-418e-9ead-1d51cb80b644)

### Discord/revolt server

https://discord.gg/8vsjyuDrSX

### server's website

https://clever-teaching.com

### server ip

wss://clever-teaching.com

**Comment by radmanplays** [comment]
your server has been added to the server list!
