### ISSUE TITLE
BBMStudios

### ISSUE THREAD

**Issue by ste932** [radmanplays/radmanplays.github.io#91]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

this is my vanilla eaglercraft server, it is hosted on my home server and via bungeecord and viaversion even if the server is in 1.20.2, you can use it via eaglercraft, I'm trying to maintain 100% uptime, I'm Italian, so If I didn't write the description well, please forgive me

### Discord/revolt server

https://discord.gg/CZAFHa6Xbj

### server ip

wss://neat-sheep-noticeably.ngrok-free.app

**Comment by radmanplays** [comment]
your server has been added!

**Comment by ste932** [comment]
can you remove the server please?
