### ISSUE TITLE
Michael

### ISSUE THREAD

**Issue by XtheRaptOr** [radmanplays/radmanplays.github.io#93]
### by making a request to add your server you must check these boxes

- [X] I know that this serverlist is only for servers that support eaglercraft or are only for eaglercraft
- [X] I know that i have to include the eaglercraft ip in the ip section not the minecraft ip
- [X] I know that by making a request to add my server to the serverlist anyone can join my server
- [X] I know that by making a request you dont make me a server and add it to the serverlist
- [ ] I just checked all of these boxes without reading the labels

### replit server or 24/7 eaglercraft server?

- [ ] the server is made in replit
- [X] the server is made in an paid,24/7 host

### about server

Michaels server is a 1 survival world where you can hang out with your friends. and play normal survival with no lag.
there are rules though.
1 No destroying any manmade structures. like player bases.
2 no spamming chat/ Lagging the server.
3 Hacks will not be tolerated.

have fun .

### server ip

wss://michaels.server.com

**Comment by radmanplays** [comment]
fake ip
